### ISSUE TITLE
xlims in ggkmTable

### ISSUE THREAD

**Issue by shmilt** [dmenne/dmisc2#1]
Hi, your version of ggkmTable works great, but I noticed it has no "xlims" parameter as in the original version of ggkmTable. It's very useful to set the limits of x axis instead of 0 to maximum follow up time.
(BTW: less relevant for me, but worth to mention- ylims also exist in the original version).
Do you have any idea how to put it back to the function?
Thanks!
S.

**Comment by dmenne** [comment]
Thanks, I will add this, but I have a few other problems with the code that I will try to solve. As a temporary workaround , you can simply do `ggkmTable(.....) + xlim(0,100)` in your code.

**Comment by shmilt** [comment]
Thank you!
Tried your solution and unfortunately it doesn't work, with this error message:
`Error in ggkmTable(...)  : 
  non-numeric argument to binary operator`
Any idea?

**Comment by dmenne** [comment]
Sorry, had not checked this. Will try later.
