### ISSUE TITLE
Roxygen2 to provide documentation

### ISSUE THREAD

**Issue by MarcinKosinski** [dmenne/dmisc2#3]
Why this package has no documentation and `man` folder?
You have `roxygen2`-style documentation in `*.R` files but it looks like you didn't build package using `roxygen2` because there is no `man` folder.

**Comment by dmenne** [comment]
I was not sure if I should include it, because it is a one-button press in RStudio to rebuild.

**Comment by MarcinKosinski** [comment]
When I go `devtools::install_github(path to your packae on github)` I don't
receive your Rproject and I can not use RStudio to rebuild :<

2015-11-04 18:23 GMT+01:00 Dieter Menne notifications@github.com:

**Comment by dmenne** [comment]
Strange. Rproject is there (check the directory).

**Comment by MarcinKosinski** [comment]
Thanks good to know. I was installing your package to use `ggkm` function
but I still think that survMisc:::autoplot() looks better for me :P

2015-11-05 8:15 GMT+01:00 Dieter Menne notifications@github.com:

**Comment by dmenne** [comment]
No doubt. Most of these things in Dmisc are of historical value, the only function I see no alternative even in ggplot world is "lattice panel with paging".

**Comment by MarcinKosinski** [comment]
I've moved to survminer::ggsurvplot now
